// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ortymid/t2-http/market (interfaces: ProductService)

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	market "github.com/ortymid/t2-http/market"
	reflect "reflect"
)

// MockProductService is a mock of ProductService interface
type MockProductService struct {
	ctrl     *gomock.Controller
	recorder *MockProductServiceMockRecorder
}

// MockProductServiceMockRecorder is the mock recorder for MockProductService
type MockProductServiceMockRecorder struct {
	mock *MockProductService
}

// NewMockProductService creates a new mock instance
func NewMockProductService(ctrl *gomock.Controller) *MockProductService {
	mock := &MockProductService{ctrl: ctrl}
	mock.recorder = &MockProductServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockProductService) EXPECT() *MockProductServiceMockRecorder {
	return m.recorder
}

// AddProduct mocks base method
func (m *MockProductService) AddProduct(arg0 *market.Product) (*market.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddProduct", arg0)
	ret0, _ := ret[0].(*market.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddProduct indicates an expected call of AddProduct
func (mr *MockProductServiceMockRecorder) AddProduct(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProduct", reflect.TypeOf((*MockProductService)(nil).AddProduct), arg0)
}

// DeleteProduct mocks base method
func (m *MockProductService) DeleteProduct(arg0 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProduct", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProduct indicates an expected call of DeleteProduct
func (mr *MockProductServiceMockRecorder) DeleteProduct(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProduct", reflect.TypeOf((*MockProductService)(nil).DeleteProduct), arg0)
}

// Product mocks base method
func (m *MockProductService) Product(arg0 int) (*market.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Product", arg0)
	ret0, _ := ret[0].(*market.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Product indicates an expected call of Product
func (mr *MockProductServiceMockRecorder) Product(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Product", reflect.TypeOf((*MockProductService)(nil).Product), arg0)
}

// Products mocks base method
func (m *MockProductService) Products() ([]*market.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Products")
	ret0, _ := ret[0].([]*market.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Products indicates an expected call of Products
func (mr *MockProductServiceMockRecorder) Products() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Products", reflect.TypeOf((*MockProductService)(nil).Products))
}

// ReplaceProduct mocks base method
func (m *MockProductService) ReplaceProduct(arg0 *market.Product) (*market.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceProduct", arg0)
	ret0, _ := ret[0].(*market.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplaceProduct indicates an expected call of ReplaceProduct
func (mr *MockProductServiceMockRecorder) ReplaceProduct(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceProduct", reflect.TypeOf((*MockProductService)(nil).ReplaceProduct), arg0)
}
